// src/view/html-components/loading-screen/loading-screen.tsx
import type { JSX } from "preact";
import styles from "./style.module.scss";

export type LoadingScreenProps = {
  loadingPercentage: number;
};

export const LoadingScreen = ({ loadingPercentage }: LoadingScreenProps): JSX.Element => {
  const finishedLoading = loadingPercentage === 100;
  const classNames = styles["loading"] + (finishedLoading ? " " + styles["loading--hidden"] : "");
  return (
    <div className={classNames}>
      <div className={styles["loading__inner"]}>
        <h4>Loading</h4>
        <p>{Math.round(loadingPercentage)}%</p>
        <progress value={loadingPercentage} max="100" />
      </div>
    </div>
  );
};

// src/view/svelte-components/LoadingScreen.svelte
<script module lang="ts">
  export type LoadingScreenProps = {
    loadingPercentage: number;
  };
</script>

<script lang="ts">
  let { loadingPercentage }: LoadingScreenProps = $props();
</script>

<div class={"loading"}>
  <div class={"loading__inner"}>
    <h4>Loading</h4>
    <p>{Math.round(loadingPercentage)}%</p>
    <progress value={loadingPercentage} max="100"></progress>
  </div>
</div>

<style lang="scss">
  .loading {
    position: absolute;
    display: flex;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    justify-content: center;
    align-items: center;

    &__inner {
      position: relative;
      display: flex;
      gap: 5px;
      width: 100%;
      max-width: 300px;
      flex-direction: column;
      align-items: center;
      opacity: 1;
      padding: 20px;
    }
  }
</style>
